
[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py313"]
exclude = '''
/(\.
  | \.venv
  | venv
  | build
  | dist
  | data
  | logs
  | __pycache__
  | \.git
  | \.mypy_cache
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 100
py_version = 312 # turns out the 3.13 is not supported currently
known_first_party = ["src"]
skip = [".venv", "venv", "build", "dist", "data", "logs", "__pycache__"]
combine_as_imports = true
force_sort_within_sections = true
